package ProjectEuler.Set2;

import java.util.Scanner;

/**
 * Created by Nikhil on 1/31/2017 2:28 PM.
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 'th triangle number would be . The first ten terms would be:
 Let us list the factors of the first seven triangle numbers:
 We can see that  is the first triangle number to have over five divisors.
 What is the value of the first triangle number to have over  divisors?
 */
public class P12HighlyDivisibleTriangularNumber {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int T = scanner.nextInt();
        while(T-- >0){
            int N = scanner.nextInt();
            int result = 1;
            while(getAllFactorsCount(getTrangularSum(result))<=N) result+=1;
            System.out.println("result = " + result);
        }
    }
    private static int getTrangularSum(int number){
        return (number*(number+1))/2;
    }
    private static int getAllFactorsCount(int number){
        int count = 0;
        int i = 1;
        while(i*i< number) {
            if(number%i==0){
                count+=2;
            }
            i++;
        }
        if(i*i==number){        //for case 5*5=25, 5 would be counted twice we just want it to count once.
            count++;            // Hence add other condition
        }
        return count;
    }
}
